### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kasumiko** [kasumiko/proconbot-4bslack#1]
## plan to be implemented
- Tell what contest will be held on atcoder (Callback) .
  - [x] scraping func (cron)
  - [x] update scheduled contest db (cron)
  - [x] receive query func (maybe ducktype) 
- [x] Mention of today's contest.
- [x] Notice one's rate changing
- [x] Today's problem(Return a random problem which can be solved by User).
